version: '3.8'
services:
  developer-db:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cozzyconnect
    networks:
      - SpearAndHarmmer
networks:
  SpearAndHarmmer:


